apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
        - name: wil42
          image: wil42:1@sha256:7a8d601dc95973332117529363c5e76399ac85167f6ffb01a9d8a2e03b6ae299
          ports:
            - containerPort: 8888